spring:
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: inbox-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <client-id>
            client-secret: <client-secret>

datastax.astra:
  secure-connect-bundle: connect.zip

astra:
  db:
    id: <cluster-id>
    region: europe-west1
    keyspace: main
    application:
      token: <token>
